# .eslintrc.yml
# Copyright (C) 2018-2020 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
extends: eslint:recommended
env:
  es2015: true
  node: true
overrides:
  - files:
      - browser/*
    parserOptions:
      sourceType: module
    env:
      node: false
      browser: true
ignorePatterns:
  - deploy/*
root: true
