# .eslintrc.yml
# Copyright (C) 2018 Kaz Nishimura
#
# Copying and distribution of this file, with or without modification, are
# permitted in any medium without royalty provided the copyright notice and
# this notice are preserved.  This file is offered as-is, without any warranty.
---
extends: eslint:recommended
parserOptions:
  sourceType: module
env:
  es6: true
  browser: true
overrides:
  - files:
      - etc/*.js
    parserOptions:
      sourceType: script
    env:
      browser: false
      node: true
ignorePatterns:
  - /deploy/*
root: true
